### ISSUE TITLE
Finish User Auth 

### ISSUE THREAD

**Issue by linlinliu03** [linlinliu03/StackFull#2]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by helenyueyu** [comment]
**Splash Page**
- [ ] Login and Signup buttons are too spaced out (and too small)
- [ ] Search field text should be more similar to Arial instead of Times New Roman 
- [ ] Remove blue outline from clicking the "Log in" and "Sign up" buttons

**Log In Form**
- [ ] Change font style on the "Log In" form from serif to a sans serif  
- [ ] Make errors more descriptive for the "Log In" form (rather than having all of them on the bottom of the form, see actual website errors) 
- [ ] Add more padding on the "Username" and "Password" fields 
- [ ] Remove the boldness of the font for the "Username" and "Password" fields 
- [ ] Make errors look more pretty
- [ ] When I navigate from the "Log In" form to the "Sign Up" form, error messages still persist 

**Sign Up Form**
- [ ] Separate out errors by each input field 
- [ ] Add more padding to the "Username", "Password" and "Email" fields
